In [1]:
import numpy as np
import h5py

/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [21]:
filename = 'data.h5'
f = h5py.File(filename, 'r')
f['all_img_names'][0]

1.0

In [26]:
f.close()

In [28]:
filename = 'data.h5'
f = h5py.File(filename, 'w')
dset = f.create_dataset('all_img_names', (0,5,0,0), maxshape=(None,None,None,None), dtype='float')
dset.resize(dset.shape[0]+1, axis=0)
dset.resize(dset.shape[1]+2, axis=1)
dset.resize(dset.shape[2]+3, axis=2)
dset.resize(dset.shape[3]+4, axis=3)
dset[-1:, -1:, -2:, -3:] = 12
print(dset.shape)
print(f['all_img_names'][0])

f.close()

(1, 7, 3, 4)
[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0. 12. 12. 12.]
  [ 0. 12. 12. 12.]]]


In [23]:
f['all_img_names'][0]

array([[[12.]]])

In [29]:
a = np.array([range(3)]*6)

In [31]:
a.shape

(6, 3)

In [34]:
np.array([0]*7)

array([0, 0, 0, 0, 0, 0, 0])